### ISSUE TITLE
Change number of commits made when a problem is solved.

### ISSUE THREAD

**Issue by Ponte348** [maitreya2954/LeetHub-2.0-Firefox#1]
**Is your feature request related to a problem? Please describe.**
I'm solving at least 3 problems a day and while I like having the contributions displayed on my profile, 4 contributions for 1 problem that sometimes is small clutters my contributions profile.

**Describe the solution you'd like**
Maybe change the number of commits to 1 or 2 for each problem, for example, these 4 commits that are made with every sync:
- [Create README - LeetHub](https://github.com/Ponte348/LeetCodeSolutions/commit/b98d8517c35e0d59d167f4c8385fab5c9ba8e19a)
- [Time: 470 ms (95.9%), Space: 29.1 MB (91.06%) - LeetHub](https://github.com/Ponte348/LeetCodeSolutions/commit/ee8d024c356d7128ce42aa265561ed7688d42928)
- [Update README - Topic Tags](https://github.com/Ponte348/LeetCodeSolutions/commit/995a5459cefddf68c9f0f9b7f8bf4599c79602d4)
- [Updated stats](https://github.com/Ponte348/LeetCodeSolutions/commit/1d7a553cd6ce3cc2199241de2dcc4dec277618e1)

could be 1 commit only, since **Time: 470 ms (95.9%), Space: 29.1 MB (91.06%) - LeetHub** is the only relevant information in any of the commits.

**Additional context**
I'm not good at js and I haven't looked at the code to see where this is all happening, so if the separate commits are there because that's the only wait it works it's fine. If given any instructions I can try to look into it myself.

**Comment by maitreya2954** [comment]
Closing this issue as fixed. Reopen if needed
