### ISSUE TITLE
Manual submission button doesnt popup after reloading submission page

### ISSUE THREAD

**Issue by msaimadhur** [maitreya2954/LeetHub-2.0-Firefox#2]
**Describe the bug**
Manual submission button doesn't show up after reloading submission page

**To Reproduce**
1. Submit a solution
2. Copy the url and load this on different tab
3. Manual submission button doesn't show up

**Expected behavior**
Button should show up.

**Comment by maitreya2954** [comment]
@msaimadhur Closed. Reopen if needed
