### ISSUE TITLE
Readme file on a leethub repository doesn't work correctly

### ISSUE THREAD

**Issue by Poweramo** [maitreya2954/LeetHub-2.0-Firefox#4]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Describe the bug**
When i go to my "my-leetcode-solutions" repository and check my readme file, rather than showing me the problems I solved and their categories like before, now it shows a long list of random characters (except for the last leetcode problem solved wich displays correctly).

**To Reproduce**
1. Go to my-leetcode-solutions repository
2. Click on Readme file
3. See a large chunk of random characters

**Expected behavior**
Show the leetcode problems I solved and their categories in the Readme file like it used to do it before.

**Screenshots**
https://github.com/user-attachments/assets/62d25edf-cd2f-40df-8832-09ce0b0399b3
(It's very large, I have only been able to screen this part)

**Additional context**
I don't know if it's in my repository only or an actual bug, but I would want to know what are the possibles reasons that can cause this issue.

**Comment by maitreya2954** [comment]
@Poweramo Can you attach your README file

**Comment by Poweramo** [comment]
Thank you for fixing the issue, it's working fine now !
